### ISSUE TITLE
remark-lint

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/snowsaw#36]
<p align="center"><img src="https://raw.githubusercontent.com/remarkjs/remark-lint/02295bc/logo.svg?sanitize=true" width="20%" /></p>

> Epic: #33 
> Depends on #47 #49 

Integrate [remark-lint][] which is built on [remark][], the powerful Markdown processor powered by plugins such as remark-lint.

> Ensuring the markdown you (and contributors) write is of great quality will provide better rendering in all the different markdown parsers, and makes sure less refactoring is needed afterwards.

remark-lint can be used through [remark-cli][npm-remark-cli] through a preset. This preset will be [remark-preset-lint-arcticicestudio][gh-remark-preset-lint-arcticicestudio], the custom preset that implements the [Arctic ice Studio Markdown Style Guide][styleguide-markdown].

Since the custom preset is still in major version `0` note that the version range should be `>=0.x.x <1.0.0` to avoid NPM's  “SemVer Major Zero Caveat”. When defining package versions with the the carat `^` or tilde `~` range selector it won't affect packages with a major version of `0`. NPM will resolve these packages to their exact version until the major version is greater or equal to `1`.
To avoid this caveat the more detailed version range `>=0.x.x <1.0.0` should be used to resolve all versions greater or equal to `0.x.x` but less than `1.0.0`. This will always use the latest `0.x.x` version and removes the need to increment the version manually on each new release.

<p align="center"><img src="https://raw.githubusercontent.com/remarkjs/remark-lint/02295bc/screenshot.png" /></p>

### Configuration

The `.remarkrc.js` configuration file will be placed in the project root as well as the `.remarkignore` file to also define ignore pattern.

### NPM script/task

To allow to run the Markdown linting separately a `lint:md` npm script/task will be added to be included in the main `lint` script flow.

## Tasks

- [x] Install [remark-cli][npm-remark-cli] and [remark-preset-lint-arcticicestudio][npm-remark-preset-lint-arcticicestudio] packages to `devDependencies`.
- [x] Implement `.remarkrc.js` configuration file.
- [x] Implement `.remarkignore` ignore pattern file.
- [x] Implement npm `lint:md` script/task.
- [x] Lint current code base for the first time and fix possible Markdown style guide violations.

[remark]: https://remark.js.org
[remark-lint]: https://github.com/remarkjs/remark-lint
[npm-remark-cli]: https://www.npmjs.com/package/remark-cli
[npm-remark-preset-lint-arcticicestudio]: https://www.npmjs.com/package/remark-preset-lint-arcticicestudio
[gh-remark-preset-lint-arcticicestudio]: https://github.com/arcticicestudio/remark-preset-lint-arcticicestudio
[styleguide-markdown]: https://arcticicestudio.github.io/styleguide-markdown

**Comment by arcticicestudio** [comment]
> Resolved in #54 (acd0df4f769a739b9c5724b6de2735a59d6f9e40)
