### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/snowsaw#37]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48644231-4556d780-e9e2-11e8-862e-e8ce630fd0ba.png" width="30%" /></p>

> Epic: #33 
> Depends on #47 #49 

Integrate [Prettier][], the opinionated code formatter with support for many languages and integrations with most editors. It ensures that all outputted code conforms to a consistent style.

### Configuration

This is one of the main features of Prettier: It already provides the best and recommended style configurations of-out-the-box™.
The only option we will change is the [print width][prettier-docs-pwidth]. It is set to 80 by default which not up-to-date for modern screens (might only be relevant when working in terminals only like e.g. with Vim). It'll be changed to 120 used by all of [_Arctic Ice Studio's_ style guides][gh-search-repo-stylg].
The `prettier.config.js` configuration file will be placed in the project root as well as the `.prettierignore` file to also define ignore pattern.

### NPM script/task

To allow to format all sources a `format:pretty` npm script/task will be added to be included in the main `format` script flow.

## Tasks

- [ ] Install [prettier][npm-prettier] package.
- [ ] Implement `prettier.config.js` configuration file.
- [ ] Implement `.prettierignore` ignore pattern file.
- [ ] Implement NPM `format:pretty` script/task.
- [ ] Format current code base for the first time and fix possible style guide violations using the configured linters of the project.

[npm-prettier]: https://www.npmjs.com/package/prettier
[prettier]: https://prettier.io
[prettier-blog-1.15-mdx]: https://prettier.io/blog/2018/11/07/1.15.0.html#mdx
[prettier-docs-pwidth]: https://prettier.io/docs/en/options.html#print-width
[gh-search-repo-stylg]: https://github.com/arcticicestudio?tab=repositories&q=styleguide&type=source

**Comment by arcticicestudio** [comment]
> Resolved in #55 (be3e59af1acf35b3586c07cf012e41aa7f3d2f5d)
