### ISSUE TITLE
Initial repository clean up for Go rewrite

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/snowsaw#49]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/59963238-8838da80-94f0-11e9-8857-4322932bdb9c.png" width="20%" /></p>

> Epic: #33 
> Blocks #34 #35 #36 #37 #38 #39 #42 #43 #44 #45 #46 #47 #48

In order to start the [Go project rewrite][gh-33] from scratch the current repository structure and files should be reset to a clean state to remove all references to the previous implementations, documentations and project structure/layout.

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/59963372-8cfe8e00-94f2-11e9-85e2-b140a889d26e.png" width="12%" /></p>

Starting from a „fresh“ state allows to build the project up with the correct structure and design pattern as if there were leftovers from the previous repository data resulting in mixed files and folders.

This ticket **must be resolved first before all other tickets** also bound to the epic #33!
See the [corresponding milestone][mst] for more details about the implementation/resolve order.

#### Tasks

- [x] [`.idea/`][tree-idea] — Delete the whole folder, the files are scoped for _Pycharm Community Edition_ and will be replaced with the correct files for _IntelliJ Ultimate Edition_ with the [official Go plugin][jb-go] ([Goland][]) later on.
- [x] [`assets/`][tree-ast] — Delete the whole folder, all assets will be redesigned and added again later on.
- [x] [`bin/`][tree-bin] — Delete the whole folder, the script is part of the Python implementation and represented the entry point of the app.
- [x] [`snowsaw/`][tree-lib] — Delete the whole folder, includes the main Python app and API implementations.
- [x] [`.editorconfig`][tree-ec] — Delete the file, it will be recreated in #38 to match the new project layout and latest _Arctic Ice Studio_ style guides.
- [x] [`.gitignore`][tree-ignore] — Delete the file, it will be recreated in #35 to match the new project layout and latest _Arctic Ice Studio_ project design standards/guidelines.
- [x] [`CHANGELOG.md`][tree-cl] — Delete the file, it will be recreated later on to match the new project layout and latest _Arctic Ice Studio_ project design standards/guidelines.
- [x] [`README.md`][tree-rdm] — Delete the file, it will be recreated later on to match the new project layout and latest _Arctic Ice Studio_ project design standards/guidelines including the new project assets (logo, repository hero etc.).

[gh-33]: https://github.com/arcticicestudio/snowsaw/issues/33
[mst]: https://github.com/arcticicestudio/snowsaw/milestone/5
[jb-go]: https://plugins.jetbrains.com/plugin/9568-go
[goland]: https://www.jetbrains.com/go
[tree-idea]: https://github.com/arcticicestudio/snowsaw/tree/bc54e5136be27f8037de5bbc2f046f37eb036274/.idea
[tree-ast]: https://github.com/arcticicestudio/snowsaw/tree/bc54e5136be27f8037de5bbc2f046f37eb036274/assets
[tree-bin]: https://github.com/arcticicestudio/snowsaw/tree/bc54e5136be27f8037de5bbc2f046f37eb036274/bin
[tree-lib]: https://github.com/arcticicestudio/snowsaw/tree/bc54e5136be27f8037de5bbc2f046f37eb036274/snowsaw
[tree-ec]: https://github.com/arcticicestudio/snowsaw/blob/bc54e5136be27f8037de5bbc2f046f37eb036274/.editorconfig
[tree-ignore]: https://github.com/arcticicestudio/snowsaw/blob/bc54e5136be27f8037de5bbc2f046f37eb036274/.gitignore
[tree-rdm]: https://github.com/arcticicestudio/snowsaw/blob/bc54e5136be27f8037de5bbc2f046f37eb036274/README.md
[tree-cl]: https://github.com/arcticicestudio/snowsaw/blob/bc54e5136be27f8037de5bbc2f046f37eb036274/CHANGELOG.md
